# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Migration(_Azure):
    _type = "migration"
    _icon_dir = "resources/azure/migration"


class CostManagementAndBilling(_Migration):
    _icon = "cost-management-and-billing.png"


class DataBoxEdge(_Migration):
    _icon = "data-box-edge.png"


class DataBox(_Migration):
    _icon = "data-box.png"


class DatabaseMigrationServices(_Migration):
    _icon = "database-migration-services.png"


class DataboxGateway(_Migration):
    _icon = "databox-gateway.png"


class Migrate(_Migration):
    _icon = "migrate.png"


class MigrationProjects(_Migration):
    _icon = "migration-projects.png"


class RecoveryServicesVaults(_Migration):
    _icon = "recovery-services-vaults.png"


class StackEdge(_Migration):
    _icon = "stack-edge.png"


# Aliases
